### ISSUE TITLE
Problem converting TrueType font to GFX for size 128

### ISSUE THREAD

**Issue by jamesee** [ropg/truetype2gfx#10]
Hi

I used your website (https://rop.nl/truetype2gfx/) to convert FreeSansBold to GFX at size 88. Everything works. But when I increase the size to 128, numeric (0-9) works, but alphabet (ABC ... Z) does not show up.

Please assist.

**Comment by ropg** [comment]
My software just calls the Adafruit library to do the actual work. Maybe try to compile and use it manually. If that works I'll have a look...

**Comment by jamesee** [comment]
Thanks for the prompt respond.
Can you point me to the Adafruit library? Any help on how to compile will be very useful... Many thanks

**Comment by Bodmer** [comment]
The Adafruit font format uses an 8 bit signed value for the bitmap offset, this means large fonts cannot be encoded or rendered correctly. This is a limitation of the Adafruit format and not this encoder software.

**Comment by ropg** [comment]
Hi Bodmer!

Thank you...

(Been working with your code with the sprite library a lot. Have a windowing sprite/direct abstraction layer done and expect to do  some work soon to make sprite-in-sprite renders faster and support transparency. Can you mail me at rop ~at rop _dot nl so I can make sure you see it when it's done?)
