### ISSUE TITLE
truetype2gfx problem

### ISSUE THREAD

**Issue by BHeadley58** [ropg/truetype2gfx#11]
Hi,
Just tried to use truetype2gfx to import/convert a font (lazenby_smooth.ttf) to an Arduino gfx file, but the resulting .h file is gibberish. Tried a couple of different Lazenby .ttf files with the same results. The font displays correctly on the utility, changing the font size changes the display size, etc. Just the export to GFX generates garbage.
The default fonts generate a proper .h file, respectfully.
Windows 10 laptop.
Any ideas?

**Comment by ropg** [comment]
Can you better define 'gibberish'? What exactly happens?

**Comment by BHeadley58** [comment]
The output file has no format, just a bunch of random characters like
Chinese or Japanese. Almost like a binary dump. If I try the 'default' font
choices, it builds an output .h file as expected.
The Laserby fonts are the old style PC fonts, similar to the characters
printed along the bottom edge of personal checks (like are those still
around? Lol)

**Comment by BHeadley58** [comment]
I import the file, the utility displays the font correctly and the test
message is okay. I can change point size and it shows the size change

**Comment by ropg** [comment]
Are you able to use the Adafruit tool manually to see what happens? My stuff is just a frontend...

Otherwise I'll have a look once I'm ready with some of the stuff I'm working on now...

**Comment by BHeadley58** [comment]
Sorry, I'm not sure what Adafruit tool you're referring to - is there a
downloadable tool that does the conversion for PC?

**Comment by ropg** [comment]
`fontconvert` from [here](https://github.com/adafruit/Adafruit-GFX-Library). My tool is merely a web frontend for that.

**Comment by BHeadley58** [comment]
Found the problem. Was opening the file with notepad, not wordpad. Notepad
has a limitation on file size.

**Comment by ropg** [comment]
Ah... Good... All is well that ends well...
