### ISSUE TITLE
Make the .h file purely by JS (instead of PHP)

### ISSUE THREAD

**Issue by Norfeldt** [ropg/truetype2gfx#3]
Just wondering if it would be possible to generate the (GFX) .h file by javascript instead of PHP.

Looking at the source I see

```
exec("./fontconvert $font $size", $output, $retval);
	if ($retval != 0) exit();
```

So there must be some lib/script called `fontconvert` in the root? I can't find it in the repo..

**Comment by ropg** [comment]
From the README:

>2.  In this directory, add a compiled version of the Adafruit fontconvert tool (see [here](https://github.com/adafruit/Adafruit-GFX-Library/tree/master/fontconvert)) and make sure it it executable to the user that runs your webserver.

**Comment by Norfeldt** [comment]
Sorry about that.. It slipped my attention. 

I'm however not good enough to get it to work on my mac (https://github.com/adafruit/Adafruit-GFX-Library/issues/224)

**Comment by Norfeldt** [comment]
I got it working now! THX!
