### ISSUE TITLE
Resize picture using M5.Lcd.pushImages();

### ISSUE THREAD

**Issue by muaaz1** [ropg/truetype2gfx#4]
Im trying to upload image.jpg with size 320x240  but why when i want to customized the sized in coding, the image will get blurr or pixelised

for example, if my code is M5.Lcd.pushImage(0, 0, 320 ,240, (uint16_t*)wifi_jpg);  , the picture is good,

but when i resize it to M5.Lcd.pushImage(0, 0, 100 ,100, (uint16_t*)wifi_jpg);, it will be blurr and pixelised.

any help?

**Comment by ropg** [comment]
Not a clue, sorry...
