### ISSUE TITLE
I need a monospace font that display only digit for a counter

### ISSUE THREAD

**Issue by mohammadjp** [ropg/truetype2gfx#6]
Dear sir
thanks.
I need a monospace font that display only digit for a counter
I changed more than 20 monospace font from
[https://www.1001fonts.com/monospaced+bold+programming-fonts.html](url)
to gfx format.
unfortunatly changed font was not monospace 
Do you can solve this problem

**Comment by ropg** [comment]
I'm not sure I understand what you mean. If I convert something like [this](https://fonts2u.com/digital-7-mono.font) using the tool, I get something that looks very monospaced to me.

**Comment by mohammadjp** [comment]
Very thanks 
it is good
do you can introduce me some other monospace font without 7segment face

**Comment by ropg** [comment]
https://lmgtfy.com/?q=free+monospaced+ttf+fonts

**Comment by mohammadjp** [comment]
Oh my good
there is a problem in 1 digit 
i am trying to send a video

**Comment by mohammadjp** [comment]
[https://drive.google.com/file/d/10epvNaaCawMw8Uy4q0_hlynkXYhKkRVX/view?usp=drivesdk](url)

**Comment by ropg** [comment]
Says "You need permission"...

**Comment by mohammadjp** [comment]
Please check again
now this link is public
