### ISSUE TITLE
error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by Rick-OGSS** [ropg/truetype2gfx#7]
Hi, first off, your whole M5 EZ tool is great.  Kudos and thanks for all your work on it!!

I want to include a seven-segment ttf but am having some issues.  I am using VSCode with the M5 extension as the Arduino extension conflicts with it and I find that, unlike the Arduino IDE all of my methods must be defined before it is called.

For this error I found a seven seg TTF here that I want to include:
https://dafonttop.com/seven-segment.font

I used your font file builder with it and added the .h file to my project in VS Code but I get a build error as per these two snippets:

![Selection_001](https://user-images.githubusercontent.com/56748365/77835142-696f1080-7120-11ea-8273-a25010144664.png)

I tried moving the const GFXfont def to the top but that did not solve the issue.

Cheers

Rick

**Comment by ropg** [comment]
variable names cannot start with a number... ([longer story](https://stackoverflow.com/questions/342152/why-cant-variable-names-start-with-numbers))

**Comment by ropg** [comment]
--- And glad you like M5ez... We aim to please... ;)

**Comment by Rick-OGSS** [comment]
Face plant!

I missed the obvious.

Thanks for fast reply!

**Comment by Rick-OGSS** [comment]
Hi Rop,

By chance would you have some code snippets showing how the "ez.addevent"
and "ez.refresh" should work.  I have a case where I am getting real time
sensor data and only want to update one part of the screen/page, without
flickering.  I looked through all of your demo files but couldnt find
anything.

My desired sequence is to have the code retrieve the sensor values, convert
to engineering units, then update the specified values on the screen every
500ms, without flickering.

I have created a function like this in file "page1.h"

And then have it being called by my main loop in "main.ino"

Any insight, snippets or links would be greatly appreciated,

Thanks

Rick

uint16_t main_screen_update_values(){
Serial.println("updating main screen values"); //for debug use only

//fridge temperature display code to set colour, position and font then ...
// update the screen variable value

ez.canvas.println(freezer_temp_string);

ez.redraw(); //Do I redraw here?

return(500); //event update time in ms

}



void loop() {
scan_buttons(); // special button controls for incrementing/decrementing
the setpoint
read_temperature_sensors(); // read the raw values, validate and convert to
eng units

ez.addEvent(main_screen_update_values,500); // using the temp sensor
variables, update the screen every 500ms



}

**Comment by ropg** [comment]
all redraw() does is set a flag which tells the menu code to redraw once your event exits. You can't really change what the menu displays after you event exits, you only get the choice whether you want to redraw the menu. This way, you could, say, have a messageBox and then return to the menu.

Yes, one could make the menu exit, start a new menu, and whatnot. But that quickly gets hairy and runs into the limits of what M5ez was set up to do... I will give it some more though, but whatever I come up with has to keep people from messing themselves up somehow...

**Comment by Rick-OGSS** [comment]
Thanks Rop, I have been pondering and I think that I should write this
portion of the project using the M5 libraries and just use your EZ
framework for my menuing system.

Cheers,

Rick
